services:
  db:
    image: mysql:8.3
    container_name: job-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=job_matching_db
    ports:
      - "3307:3306"
    command: ["mysqld","--default-authentication-plugin=mysql_native_password","--max_connections=300"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-psecret"]
      interval: 5s
      timeout: 3s
      retries: 30

  discovery:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    image: jm-discovery:dev
    container_name: jm-discovery
    ports:
      - "8761:8761"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: jm-user:dev
    container_name: jm-user
    ports:
      - "8081:8081"
    environment:
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
    depends_on:
      db:
        condition: service_healthy
      discovery:
        condition: service_started

  job-service:
    build:
      context: .
      dockerfile: job-service/Dockerfile
    image: jm-job:dev
    container_name: jm-job
    ports:
      - "8082:8082"
    environment:
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
    depends_on:
      db:
        condition: service_healthy
      discovery:
        condition: service_started

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: jm-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false       # DEV: tắt auth
      - ES_JAVA_OPTS=-Xms1g -Xmx1g         # Nếu máy yếu: -Xms512m -Xmx512m
    ports:
      - "9200:9200"    # HTTP API
      - "9300:9300"    # Transport
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 20


volumes:
  mysql_data:
  esdata:
